export enum PathEnum {
  HOME = '/',
  PURPOSE = '/proposito',
  SOCIAL_IMPACT = '/impacto-social',
  TEXT_DIRECTOR_PRESIDENT = '/texto-diretor-presidente',
  TEXT_BOARD = '/texto-diretoria',
  INSIDE_OUT = '/de-dentro-para-fora',
  X_RAY = '/raio-x',
  RETROSPECTIVE = '/restrospectiva-2022',
  DOCTORS_JOY_MEDIA = '/doutores-da-alegria-na-midia',
  EMBRANCE_CAUSE = '/abrace-a-causa',
  ACCOUNTABILITY = '/prestacao-de-contas',
  TEAM = '/equipe',
  PARTNERS = '/parceiros',
  FILES = '/expedientes',
}