import React from "react";
import { useTranslation } from "react-i18next";
import {
  GridContainer,
  GridItemOne,
  GridItemTree,
  GridItemTwo,
  PartnersContainer,
} from "./partners.styles";
import { useNavigate } from "react-router-dom";
import {
  ButtonContainer,
  GlobalBackButton,
  GlobalNextButton,
  TextContainer,
  Typography,
} from "../../styles/global.styles";
import { ReactComponent as NextButton } from "../../../public/assets/setinha-direita.svg";
import { DalegriaFontesEnum } from "../../utils/fontes";
import { DalegriaColorsEnum } from "../../utils/colors";

export const Partners: React.FC = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <PartnersContainer>
      <TextContainer
        textAlign="center"
        justifyContent="center"
        align="center"
        marginBottom={16}
      >
        <Typography
          fontFamily={DalegriaFontesEnum.ManualBasicS}
          textColor={DalegriaColorsEnum.LightBlue}
          lineHeight={1}
          fontSize={28}
        >
          {t("retrospective.partners.titles.one")}
        </Typography>
      </TextContainer>

      <TextContainer
        textAlign="center"
        justifyContent="center"
        align="center"
        marginBottom={16}
      >
        <Typography
          fontFamily={DalegriaFontesEnum.ManualBasicS}
          textColor={DalegriaColorsEnum.LightBlue}
          lineHeight={1}
          fontSize={28}
        >
          {t("retrospective.partners.titles.two")}
        </Typography>
      </TextContainer>

      <GridContainer>
        <GridItemOne>
          <TextContainer
            textAlign="left"
            justifyContent="center"
            align="center"
            marginBottom={16}
          >
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasicS}
              textColor={DalegriaColorsEnum.Purple}
              lineHeight={1.25}
              fontSize={16}
            >
              {t("retrospective.partners.titles.tree")}
            </Typography>
          </TextContainer>

          <TextContainer
            textAlign="left"
            justifyContent="flex-start"
            align="flex-start"
            marginBottom={16}
          >
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Purple}
              fontSize={16}
            >
              {t("retrospective.partners.list_01.item_01")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Purple}
              fontSize={16}
            >
              {t("retrospective.partners.list_01.item_02")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Purple}
              fontSize={16}
            >
              {t("retrospective.partners.list_01.item_03")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Purple}
              fontSize={16}
            >
              {t("retrospective.partners.list_01.item_04")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Purple}
              fontSize={16}
            >
              {t("retrospective.partners.list_01.item_05")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Purple}
              fontSize={16}
            >
              {t("retrospective.partners.list_01.item_06")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Purple}
              fontSize={16}
            >
              {t("retrospective.partners.list_01.item_07")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Purple}
              fontSize={16}
            >
              {t("retrospective.partners.list_01.item_08")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Purple}
              fontSize={16}
            >
              {t("retrospective.partners.list_01.item_09")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Purple}
              fontSize={16}
            >
              {t("retrospective.partners.list_01.item_10")}
            </Typography>
          </TextContainer>

          <TextContainer
            textAlign="left"
            justifyContent="center"
            align="center"
            marginBottom={16}
          >
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasicS}
              textColor={DalegriaColorsEnum.LightBlue}
              lineHeight={1.25}
              fontSize={16}
            >
              {t("retrospective.partners.titles.four")}
            </Typography>
          </TextContainer>

          <TextContainer
            textAlign="left"
            justifyContent="flex-start"
            align="flex-start"
            marginBottom={16}
          >
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.LightBlue}
              fontSize={16}
            >
              {t("retrospective.partners.list_02.item_01")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.LightBlue}
              fontSize={16}
            >
              {t("retrospective.partners.list_02.item_02")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.LightBlue}
              fontSize={16}
            >
              {t("retrospective.partners.list_02.item_03")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.LightBlue}
              fontSize={16}
            >
              {t("retrospective.partners.list_02.item_04")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.LightBlue}
              fontSize={16}
            >
              {t("retrospective.partners.list_02.item_05")}
            </Typography>
          </TextContainer>
        </GridItemOne>

        <GridItemTwo>
          <TextContainer
            textAlign="left"
            justifyContent="center"
            align="center"
            marginBottom={16}
          >
            <Typography
              fontFamily={DalegriaFontesEnum.StdBold}
              textColor={DalegriaColorsEnum.Black}
              lineHeight={1.25}
              fontSize={16}
            >
              {t("retrospective.partners.titles.five")}
            </Typography>
          </TextContainer>

          <TextContainer
            textAlign="left"
            justifyContent="center"
            align="center"
          >
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasicS}
              textColor={DalegriaColorsEnum.Pink}
              lineHeight={1.25}
              fontSize={16}
            >
              {t("retrospective.partners.titles.ten")}
            </Typography>
          </TextContainer>

          <TextContainer
            textAlign="left"
            justifyContent="flex-start"
            align="flex-start"
            marginBottom={16}
          >
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Pink}
              fontSize={16}
            >
              {t("retrospective.partners.list_03.item_01")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Pink}
              fontSize={16}
            >
              {t("retrospective.partners.list_03.item_02")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Pink}
              fontSize={16}
            >
              {t("retrospective.partners.list_03.item_03")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Pink}
              fontSize={16}
            >
              {t("retrospective.partners.list_03.item_04")}
            </Typography>
          </TextContainer>

          <TextContainer
            textAlign="left"
            justifyContent="center"
            align="center"
          >
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasicS}
              textColor={DalegriaColorsEnum.Red}
              lineHeight={1.25}
              fontSize={16}
            >
              {t("retrospective.partners.titles.eleven")}
            </Typography>
          </TextContainer>

          <TextContainer
            textAlign="left"
            justifyContent="flex-start"
            align="flex-start"
            marginBottom={16}
          >
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={16}
            >
              {t("retrospective.partners.list_04.item_01")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={16}
            >
              {t("retrospective.partners.list_04.item_02")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={16}
            >
              {t("retrospective.partners.list_04.item_03")}
            </Typography>
          </TextContainer>

          <TextContainer
            textAlign="left"
            justifyContent="center"
            align="center"
          >
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasicS}
              textColor={DalegriaColorsEnum.Purple}
              lineHeight={1.25}
              fontSize={16}
            >
              {t("retrospective.partners.titles.six")}
            </Typography>
          </TextContainer>

          <TextContainer
            textAlign="left"
            justifyContent="flex-start"
            align="flex-start"
            marginBottom={16}
          >
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Purple}
              fontSize={16}
            >
              {t("retrospective.partners.list_05.item_01")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Purple}
              fontSize={16}
            >
              {t("retrospective.partners.list_05.item_02")}
            </Typography>
          </TextContainer>

          <TextContainer
            textAlign="left"
            justifyContent="center"
            align="center"
          >
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasicS}
              textColor={DalegriaColorsEnum.LightBlue}
              lineHeight={1.25}
              fontSize={14}
            >
              {t("retrospective.partners.titles.seven")}
            </Typography>
          </TextContainer>

          <TextContainer
            textAlign="left"
            justifyContent="flex-start"
            align="flex-start"
            marginBottom={14}
          >
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.LightBlue}
              fontSize={14}
            >
              {t("retrospective.partners.list_06.item_01")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.LightBlue}
              fontSize={14}
            >
              {t("retrospective.partners.list_06.item_02")}
            </Typography>
          </TextContainer>
        </GridItemTwo>
        <GridItemTree>
          <TextContainer
            textAlign="left"
            justifyContent="flex-start"
            align="flex-start"
          >
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasicS}
              textColor={DalegriaColorsEnum.Red}
              lineHeight={1.25}
              fontSize={14}
            >
              {t("retrospective.partners.titles.eight")}
            </Typography>
          </TextContainer>
          <TextContainer
            textAlign="left"
            justifyContent="flex-start"
            align="flex-start"
            marginBottom={24}
          >
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              lineHeight={1.25}
              fontSize={14}
            >
              {t("retrospective.partners.titles.nine")}
            </Typography>
          </TextContainer>

          <TextContainer
            textAlign="left"
            justifyContent="flex-start"
            align="flex-start"
          >
            <Typography
              fontFamily={DalegriaFontesEnum.StdBold}
              textColor={DalegriaColorsEnum.Red}
              lineHeight={1.25}
              fontSize={14}
            >
              {t("retrospective.partners.titles.twelve")}
            </Typography>
          </TextContainer>
          <TextContainer
            textAlign="left"
            justifyContent="flex-start"
            align="flex-start"
            marginBottom={16}
          >
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={16}
            >
              {t("retrospective.partners.list_07.item_01")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={16}
            >
              {t("retrospective.partners.list_07.item_02")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={16}
            >
              {t("retrospective.partners.list_07.item_03")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={16}
            >
              {t("retrospective.partners.list_07.item_04")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={16}
            >
              {t("retrospective.partners.list_07.item_05")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={16}
            >
              {t("retrospective.partners.list_07.item_06")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={16}
            >
              {t("retrospective.partners.list_07.item_07")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={14}
            >
              {t("retrospective.partners.list_07.item_08")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={16}
            >
              {t("retrospective.partners.list_07.item_09")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={16}
            >
              {t("retrospective.partners.list_07.item_10")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={16}
            >
              {t("retrospective.partners.list_07.item_11")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={16}
            >
              {t("retrospective.partners.list_07.item_12")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={16}
            >
              {t("retrospective.partners.list_07.item_13")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={16}
            >
              {t("retrospective.partners.list_07.item_14")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={16}
            >
              {t("retrospective.partners.list_07.item_15")}
            </Typography>
          </TextContainer>

          <TextContainer
            textAlign="left"
            justifyContent="flex-start"
            align="flex-start"
          >
            <Typography
              fontFamily={DalegriaFontesEnum.StdBold}
              textColor={DalegriaColorsEnum.Red}
              lineHeight={1.25}
              fontSize={14}
            >
              {t("retrospective.partners.titles.thirteen")}
            </Typography>
          </TextContainer>
          <TextContainer
            textAlign="left"
            justifyContent="flex-start"
            align="flex-start"
            marginBottom={16}
          >
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={16}
            >
              {t("retrospective.partners.list_08.item_01")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Red}
              fontSize={16}
            >
              {t("retrospective.partners.list_08.item_02")}
            </Typography>
          </TextContainer>

        </GridItemTree>
      </GridContainer>

      <ButtonContainer>
        <GlobalBackButton onClick={() => navigate("/equipe")}>
          <NextButton width={50} height={50} />
        </GlobalBackButton>

        <GlobalNextButton onClick={() => navigate("/expedientes")}>
          <NextButton width={50} height={50} />
        </GlobalNextButton>
      </ButtonContainer>
    </PartnersContainer>
  );
};
