import React from "react";
import { useTranslation } from "react-i18next";
import {
  AccountabilityContainer,
  AccountabilityContainerTwo,
  BackgroundPink,
  InformationsContainer,
  LeftSide,
  RightSide,
} from "../../../accountability.styles";
import { useNavigate } from "react-router-dom";
import {
  ButtonContainer,
  GlobalBackButton,
  GlobalNextButton,
  TextContainer,
  Typography,
} from "../../../../../styles/global.styles";
import { ReactComponent as NextButton } from "../../../../../../public/assets/setinha-direita.svg";
import { AccountabilityHeader } from "../../AccountabilityHeader";
import { DalegriaFontesEnum } from "../../../../../utils/fontes";
import { DalegriaColorsEnum } from "../../../../../utils/colors";
import { PercentSquare } from "../../../../../components/PercentSquare";

export const AccountabilityTwo: React.FC = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <>
      <AccountabilityHeader />
      <AccountabilityContainerTwo>
        <BackgroundPink>
          <TextContainer
            textAlign="left"
            justifyContent="flex-start"
            align="flex-start"
            marginBottom={16}
          >
            <Typography
              fontFamily={DalegriaFontesEnum.ManualBasic}
              textColor={DalegriaColorsEnum.Purple}
              lineHeight={1}
              fontSize={28}
            >
              {t("retrospective.accountability.subtitle_02")}
            </Typography>
          </TextContainer>
          <TextContainer
            textAlign="left"
            justifyContent="flex-start"
            align="flex-start"
            marginBottom={16}
          >
            <Typography
              fontFamily={DalegriaFontesEnum.StdLight}
              textColor={DalegriaColorsEnum.Purple}
              lineHeight={1}
              fontSize={14}
            >
              {t("retrospective.accountability.january_to_december")}
            </Typography>
          </TextContainer>
        </BackgroundPink>
      </AccountabilityContainerTwo>
      <InformationsContainer>
        <LeftSide>
          <TextContainer
            textAlign="left"
            justifyContent="flex-start"
            align="flex-start"
            marginBottom={32}
            chooseWidth={100}
          >
            <PercentSquare
              chooseWidth={42}
              chooseBackgroundColor={DalegriaColorsEnum.Yellow}
              chooseTextColor={DalegriaColorsEnum.Black}
              text="68,6%"
            />
            <Typography
              fontFamily={DalegriaFontesEnum.StdLight}
              textColor={DalegriaColorsEnum.Black}
              lineHeight={1}
              fontSize={14}
            >
              {t("retrospective.accountability.percents.item_01")}
            </Typography>
          </TextContainer>
          <TextContainer
            textAlign="left"
            justifyContent="flex-start"
            align="flex-start"
            marginBottom={32}
            chooseWidth={100}
          >
            <PercentSquare
              chooseWidth={48}
              chooseBackgroundColor={DalegriaColorsEnum.Purple}
              chooseTextColor={DalegriaColorsEnum.White}
              text="18,20%"
            />
            <Typography
              fontFamily={DalegriaFontesEnum.StdLight}
              textColor={DalegriaColorsEnum.Black}
              lineHeight={1}
              fontSize={14}
            >
              {t("retrospective.accountability.percents.item_02")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.StdLight}
              textColor={DalegriaColorsEnum.Black}
              lineHeight={1}
              fontSize={10}
            >
              {t("retrospective.accountability.percents.sub_item_02")}
            </Typography>
          </TextContainer>
          <TextContainer
            textAlign="left"
            justifyContent="flex-start"
            align="flex-start"
            marginBottom={32}
            chooseWidth={100}
          >
            <PercentSquare
              chooseWidth={42}
              chooseBackgroundColor={DalegriaColorsEnum.Pink}
              chooseTextColor={DalegriaColorsEnum.White}
              text="3,50%"
            />
            <Typography
              fontFamily={DalegriaFontesEnum.StdLight}
              textColor={DalegriaColorsEnum.Black}
              lineHeight={1}
              fontSize={14}
            >
              {t("retrospective.accountability.percents.item_03")}
            </Typography>
            <Typography
              fontFamily={DalegriaFontesEnum.StdLight}
              textColor={DalegriaColorsEnum.Black}
              lineHeight={1}
              fontSize={10}
            >
              {t("retrospective.accountability.percents.sub_item_03")}
            </Typography>
          </TextContainer>
          <TextContainer
            textAlign="left"
            justifyContent="flex-start"
            align="flex-start"
            marginBottom={32}
            chooseWidth={100}
          >
            <PercentSquare
              chooseWidth={42}
              chooseBackgroundColor={DalegriaColorsEnum.Red}
              chooseTextColor={DalegriaColorsEnum.White}
              text="3,20%"
            />
            <Typography
              fontFamily={DalegriaFontesEnum.StdLight}
              textColor={DalegriaColorsEnum.Black}
              lineHeight={1}
              fontSize={14}
            >
              {t("retrospective.accountability.percents.item_04")}
            </Typography>
          </TextContainer>
          <RightSide>
            <TextContainer
              textAlign="left"
              justifyContent="flex-start"
              align="flex-start"
              marginBottom={32}
              chooseWidth={130}
            >
              <PercentSquare
                chooseWidth={42}
                chooseBackgroundColor={DalegriaColorsEnum.LightBlue}
                chooseTextColor={DalegriaColorsEnum.Black}
                text="2,50%"
              />
              <Typography
                fontFamily={DalegriaFontesEnum.StdLight}
                textColor={DalegriaColorsEnum.Black}
                lineHeight={1}
                fontSize={14}
              >
                {t("retrospective.accountability.percents.item_05")}
              </Typography>
            </TextContainer>
            <TextContainer
              textAlign="left"
              justifyContent="flex-start"
              align="flex-start"
              marginBottom={32}
              chooseWidth={150}
            >
              <PercentSquare
                chooseWidth={42}
                chooseBackgroundColor={DalegriaColorsEnum.Green}
                chooseTextColor={DalegriaColorsEnum.White}
                text="1,80%"
              />
              <Typography
                fontFamily={DalegriaFontesEnum.StdLight}
                textColor={DalegriaColorsEnum.Black}
                lineHeight={1}
                fontSize={14}
              >
                {t("retrospective.accountability.percents.item_07")}
              </Typography>
              <Typography
                fontFamily={DalegriaFontesEnum.StdLight}
                textColor={DalegriaColorsEnum.Black}
                lineHeight={1}
                fontSize={10}
              >
                {t("retrospective.accountability.percents.sub_item_07")}
              </Typography>
            </TextContainer>
            <TextContainer
              textAlign="left"
              justifyContent="flex-start"
              align="flex-start"
              marginBottom={32}
              chooseWidth={130}
            >
              <PercentSquare
                chooseWidth={42}
                chooseBackgroundColor={DalegriaColorsEnum.Salmon}
                chooseTextColor={DalegriaColorsEnum.Black}
                text="68,6%"
              />
              <Typography
                fontFamily={DalegriaFontesEnum.StdLight}
                textColor={DalegriaColorsEnum.Black}
                lineHeight={1}
                fontSize={14}
              >
                {t("retrospective.accountability.percents.item_05")}
              </Typography>
            </TextContainer>
            <TextContainer
              textAlign="left"
              justifyContent="flex-start"
              align="flex-start"
              marginBottom={32}
              chooseWidth={130}
            >
              <PercentSquare
                chooseWidth={42}
                chooseBackgroundColor={DalegriaColorsEnum.DarkBlue}
                chooseTextColor={DalegriaColorsEnum.White}
                text="0,20%"
              />
              <Typography
                fontFamily={DalegriaFontesEnum.StdLight}
                textColor={DalegriaColorsEnum.Black}
                lineHeight={1}
                fontSize={14}
              >
                {t("retrospective.accountability.percents.item_08")}
              </Typography>
              <Typography
                fontFamily={DalegriaFontesEnum.StdLight}
                textColor={DalegriaColorsEnum.Black}
                lineHeight={1}
                fontSize={10}
              >
                {t("retrospective.accountability.percents.sub_item_08")}
              </Typography>
            </TextContainer>
          </RightSide>
        </LeftSide>
        <ButtonContainer>
          <GlobalBackButton onClick={() => navigate("/prestacao-de-contas-01")}>
            <NextButton width={50} height={50} />
          </GlobalBackButton>

          <GlobalNextButton onClick={() => navigate("/prestacao-de-contas-03")}>
            <NextButton width={50} height={50} />
          </GlobalNextButton>
        </ButtonContainer>
      </InformationsContainer>
    </>
  );
};
